name: Autoupdate Alpa repository

on:
  schedule:
    # runs every 5 days
    - cron: "0 0 */5 * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Autoupdate Alpa repository
        uses: alpa-team/autoupdate-alpa-repo@main
        with:
          email-name: alpa.dev.team@gmail.com
          smtp-address: smtp.gmail.com
          email-password: ${{ secrets.ALPA_MAIL_BOT_PASSWORD }}
          debug: true
